### ISSUE TITLE
Unable to connect to Mongodb Atlas 

### ISSUE THREAD

**Issue by copenat** [wso2-ballerina/module-mongodb#39] opened 2018-10-22 08:33 UTC
**Description:**
MongoDB's new hosted service Atlas is getting alot of publicity. I'm trying to use Ballerina to connect but I cannot. Worked with the Ballerina team but still no joy. Documentation around this package is quite weak especially the 'options'. Can we get docs on connecting to Atlas please?

**Comment by Manuri** [comment] 2018-10-31 08:22
@copenat As discussed on slack, we'll look into this issue. Documentation improvements will be done under https://github.com/wso2-ballerina/package-mongodb/issues/38

**Comment by Manuri** [comment] 2018-10-31 19:18
@copenat I created a Mongo Atlas cluster under a free account and was able to successfully connect to the cluster and insert some data with the following program.

I had to whitelist my IP address in the cluster settings in order to do this. 

```ballerina
import wso2/mongodb;


public function main() {
    endpoint mongodb:Client conn {
        dbName: "test",
        //options: { url:"mongodb+srv://test1:test1@cluster0-gyqsg.mongodb.net/test?retryWrites=true" }
        options : { url: "mongodb://test1:test1@cluster0-shard-00-00-gyqsg.mongodb.net:27017,cluster0-shard-00-01-gyqsg.mongodb.net:27017,cluster0-shard-00-02-gyqsg.mongodb.net:27017/test?ssl=true&replicaSet=Cluster0-shard-0&authSource=admin&retryWrites=true"}
    };

    json document = { "name": "Tom", "age": "21" };
    _ = conn->insert("students", document);
    conn.stop();
}
```
Both standard and SRV connection strings worked for me. 

Also, I was able to reproduce your error,
```bash
error: ballerina/runtime:CallFailedException, message: call failed
        at main(mongo-atlas-test.bal:11)
caused by error, message: 2
        at wso2/mongodb:0.0.0:init(endpoint.bal:28)

```
With following endpoint config.
```ballerina
endpoint mongodb:Client conn {
        host: "cluster0-shard-00-00-gyqsg.mongodb.net:27017,cluster0-shard-00-01-gyqsg.mongodb.net:27017,cluster0-shard-00-02-gyqsg.mongodb.net:27017",
        dbName: "test",
        username: "test1",
        password: "test1",
        options: {authSource : "admin", sslEnabled: true}
    };
```

Even after fixing the issue related to this, I was having issues in connecting with this endpoint config.
I'll look into that.

Until then, can you try with  a sample program similar to what I have provided at the beginning and see if works for you?

**Comment by Manuri** [comment] 2018-11-08 13:17
Great! 
For now I have written a [blog post ](https://medium.com/@Manuri/lets-connect-to-mongodb-atlas-with-ballerina-8fd46f168fb6) on this. I think it would be a good idea to have a ballerina guide as well for this. 
I'll keep track of that.

Since the problem is resolved, I'm closing this issue based on your feedback.

**Closed by Manuri** 2018-11-08 13:17 UTC
